export function reading({panel,detail}){
return panel('เป้าหมาย: อธิบายได้ก่อนจำคำสั่ง','<p>ไม่ต้องอ่านรวดเดียวทั้งเว็บครับ อ่านทีละรอบแล้วลองพูดด้วยภาษาตัวเองว่าแต่ละส่วนทำอะไร เวลาประมาณด้านล่างปรับตามจังหวะของตัวเองได้</p><a class="button" href="#quick">มีแค่ 30 นาที เริ่มตรงนี้ →</a>')+
'<section id="quick">'+panel('รอบแรก · เข้าใจภาพรวม · ประมาณ 30 นาที','<ol class="numbered"><li><a href="/agentops/modules.html#lesson-0">หัวข้อ 1 · โปรแกรมและ API</a><p>จับภาพว่าโปรแกรมส่ง request และรับ response อย่างไร</p></li><li><a href="/agentops/modules.html#lesson-1">หัวข้อ 2 · Agent และ Tool</a><p>โมเดลเลือกเครื่องมือ แล้วโปรแกรมนำไปทำงานอย่างไร</p></li><li><a href="/agentops/modules.html#lesson-3">หัวข้อ 4 · CI/CD</a><p>เวอร์ชันใหม่ผ่านการตรวจและส่งไปใช้งานอย่างไร</p></li><li><a href="/agentops/modules.html#aws-deployment">บทเสริม · Deploy บน AWS</a><p>โค้ดกลายเป็น agent ที่เรียกใช้งานได้อย่างไร แยก Build, Deploy และ Invoke</p></li></ol><p><strong>ถ้ามีเวลาน้อย ทำรอบนี้ก่อนก็พอ</strong> แล้วตอบสองคำถาม: ตอนลูกค้าคุยกับ agent เกิดอะไรขึ้น? และตอนนักพัฒนาแก้ agent แล้วส่งเวอร์ชันใหม่เกิดอะไรขึ้น?</p>'+detail('แนวคำตอบสำหรับเช็กตัวเอง','<p>คำขอผู้ใช้เข้าระบบที่รันอยู่แล้ว agent เลือกใช้เครื่องมือและตอบตามผล ส่วนการแก้เวอร์ชันใหม่ต้องเตรียมชุดรัน ตรวจคุณภาพ และส่งไปปลายทางตามขั้นตอนทีม CI/CD ไม่ได้ build ใหม่ทุกครั้งที่ผู้ใช้ส่งข้อความ</p>'))+'</section>'+
panel('รอบสอง · รู้จักชิ้นส่วน · ประมาณ 30–40 นาที','<ol class="numbered"><li><a href="/agentops/modules.html#lesson-2">หัวข้อ 3 · Git / Version</a> — รู้ได้อย่างไรว่ากำลังใช้โค้ดชุดไหน?</li><li><a href="/agentops/modules.html#lesson-4">หัวข้อ 5 · Evaluation</a> — ใช้อะไรตัดสินว่า agent ทำงานดีพอ?</li><li><a href="/agentops/modules.html#lesson-5">หัวข้อ 6 · AWS</a> — แต่ละบริการทำหน้าที่อะไร?</li><li><a href="/agentops/modules.html#lesson-6">หัวข้อ 7 · Policy</a> — ระบบตัดสินอย่างไรว่าอนุญาตให้คืนเงิน?</li><li><a href="/agentops/modules.html#lesson-7">หัวข้อ 8 · Log / Trace</a> — ถ้าทำงานผิดจะเริ่มตามจากไหน?</li></ol><p>จากนั้นเปิด <a href="/agentops/simulator.html">ห้องจำลอง</a> เดินทีละขั้น ลองอธิบายสิ่งที่จะเกิดก่อนกดถัดไป และแยกผลที่คาดหวังจากผลที่รายงาน</p>')+
panel('รอบสาม · อ่านอังกฤษและคำสั่ง · ประมาณ 20 นาที','<p>อ่าน <a href="/agentops/modules.html#lesson-8">หัวข้อ 9 · อ่านอังกฤษ</a> แล้วต่อ <a href="/agentops/basics.html">Mac + AWS CLI</a> เวลาเจอคำสั่งหรือประโยคให้จับ 4 ส่วน:</p><p><strong>ทำอะไร → กับอะไร → ที่ไหน/เวอร์ชันไหน → ควรเห็นผลอะไร</strong></p><div class="expected-box" style="padding:20px;border-radius:10px"><p lang="en"><strong>Verify that the endpoint points to the intended version.</strong></p><p>ตรวจว่า endpoint ชี้เวอร์ชันที่ต้องการ งานนี้คือดูความสัมพันธ์ endpoint กับ version ไม่ใช่สั่ง deploy ใหม่</p></div><p>ไม่ต้องรันคำสั่งจริงทุกอันระหว่างอ่าน ก่อนรันต้องรู้ว่าเป็น Terminal บน Mac หรือในแล็บ และคำสั่งมีผลกับอะไร</p>')+
panel('วิธีอ่านแต่ละหัวข้อ','<ol><li>อ่านคำอธิบายกับตัวอย่างก่อน</li><li>อ่านประโยคอังกฤษ ลองแปลเองก่อนดูคำแปล</li><li>ตอบคำถามท้ายหัวข้อก่อนเปิดเฉลย</li><li>จดเพียงสามบรรทัดในสมุดหรือโน้ตที่ใช้</li></ol><pre>สิ่งนี้คืออะไร:\nเกี่ยวกับ agent ของเราอย่างไร:\nยังสงสัยอะไร:</pre><p>เช่น Pipeline คือขั้นตอนตรวจและส่งเวอร์ชันใหม่ เกี่ยวกับงานเราตรงที่มีด่าน evaluation ก่อน staging ส่วนที่สงสัยคือด่านนี้ตรวจเคสใดบ้าง</p>')+
panel('ระหว่าง workshop ใช้เว็บอย่างไร','<p>ได้ยินศัพท์ไม่รู้จัก → <a href="/agentops/glossary.html">ค้นพจนานุกรม</a><br>งงคำสั่งหรือตัวแปร → <a href="/agentops/basics.html">เปิดพื้นฐาน Terminal/AWS CLI</a><br>เจอ error → <a href="/agentops/debug.html">เปิดรายการตรวจตามอาการ</a><br>ต้องถามผู้สอน → <a href="/agentops/talk.html">เปิดตัวอย่างประโยค</a></p><p>อ่านครบแล้วลอง <a href="/agentops/quiz.html">quiz 12 ข้อ</a> ข้อที่ผิดให้กลับไปอ่านเหตุผล เป้าหมายคือเข้าใจ ไม่ใช่รีบเก็บคะแนนเต็ม</p><p>ปุ่ม “ฉันอ่านหน้านี้แล้ว” ด้านล่างใช้จำความคืบหน้าการอ่านเท่านั้น ไม่ใช่สถานะว่าทำแล็บ AWS สำเร็จ</p>');
}

