export function basics({panel,detail,e}){
const box=(title,code,note)=>'<div class="copybox"><div><b>'+title+'</b><button class="copy" type="button">คัดลอก</button></div><pre><code>'+e(code)+'</code></pre><p>'+note+'</p><p class="copy-status" role="status"></p></div>';
return panel('เริ่มจากตรงนี้: Mac ไม่ได้มี “ภาษา AWS” แยก','<p>Mac เป็นเครื่องที่เราใช้ ส่วน Terminal คือหน้าต่างพิมพ์คำสั่ง และ shell เช่น zsh เป็นตัวอ่านคำสั่งนั้น <strong>AWS CLI</strong> คือโปรแกรมชื่อ <code>aws</code> ที่ติดตั้งเพิ่มหรือมีเตรียมไว้ในแล็บ ใช้สื่อสารกับบริการ AWS ได้ คำสั่ง AWS ส่วนใหญ่มีรูปแบบเดียวกันบน Mac กับ Linux แต่การต่อบรรทัดและตัวแปรอาจต่างจาก PowerShell</p><p>ไม่ต้องจำทุกคำสั่ง เป้าหมายแรกคือบอกได้ว่า “รันที่ไหน ใช้บัญชีไหน ทำอะไร และผลที่เห็นหมายถึงอะไร”</p>')+
panel('1 · ก่อนพิมพ์ ให้รู้ว่า Terminal อยู่ที่ไหน','<div class="grid two"><article><h3>Terminal บน Mac</h3><p>Command+Space → พิมพ์ Terminal → Enter คำสั่งจัดไฟล์มีผลกับ Mac เครื่องนี้ AWS CLI อาจยังไม่ติดตั้งและยังไม่มีสิทธิ์เข้าแล็บ</p></article><article><h3>Terminal ใน workshop</h3><p>อาจเป็น editor บน browser, CloudShell หรือสภาพแวดล้อมที่ผู้สอนเตรียมให้ คำสั่งรันบนเครื่องฝั่งนั้น ไม่ใช่ Mac และอาจมีโปรแกรม/credentials เตรียมไว้แล้ว ต้องดูคำแนะนำของแล็บจริง</p></article></div><p><strong>ถามก่อนเริ่ม:</strong> “คำสั่งชุดนี้ให้รันใน Terminal ของ workshop หรือบน Mac ครับ และแล็บเตรียม AWS CLI กับสิทธิ์ไว้ให้แล้วหรือยังครับ?”</p><p>การเปิด Console ผ่าน browser ไม่ได้ทำให้ Terminal บน Mac ล็อกอิน AWS ตามโดยอัตโนมัติ ตัวแปรที่ตั้งในหน้าต่างหนึ่งก็ไม่ได้ย้ายไปอีกเครื่อง</p>')+
panel('2 · แยกคำสั่งสามกลุ่ม','<dl><dt>คำสั่ง shell / เครื่อง เช่น pwd, ls, cd</dt><dd>ใช้ดูหรือเปลี่ยนตำแหน่งไฟล์ ไม่ใช่บริการ AWS รันที่เครื่องใดก็ทำงานในบริบทของเครื่องนั้น</dd><dt>AWS CLI เช่น aws --version</dt><dd>เริ่มด้วยโปรแกรม aws ตามด้วยตัวเลือกหรือชื่อบริการ บางคำสั่งดูข้อมูลในเครื่อง บางคำสั่งติดต่อ AWS และบางคำสั่งเปลี่ยนทรัพยากร ต้องอ่านก่อนรัน</dd><dt>Python เช่น python script.py</dt><dd>เรียก interpreter ให้รันไฟล์ script.py ไฟล์นั้นอาจอ่านข้อมูลหรือเรียก cloud ผ่าน SDK ก็ได้ อย่าคิดว่าปลอดผลข้างเคียงเพราะไม่ได้ขึ้นต้น aws</dd><dt>agentcore กับ aws ไม่ใช่โปรแกรมเดียวกัน</dt><dd>คำสั่ง agentcore ในเอกสารบางชุดมาจากเครื่องมืออีกตัว รุ่นและรูปแบบอาจต่างกัน ใช้ตาม workshop ไม่สลับแทนคำสั่ง aws อัตโนมัติ</dd></dl>')+
panel('3 · ห้าคำสั่งแรก ไม่ต้องมีบัญชี AWS',
box('Terminal · ดูตำแหน่ง','pwd','ผลเป็น path เช่น /Users/ชื่อผู้ใช้ บอก directory ปัจจุบัน ถ้าเป็นเครื่องแล็บ path อาจต่างไป')+
box('Terminal · ดูรายชื่อไฟล์','ls','ดูว่าไฟล์หรือโฟลเดอร์ที่บทเรียนอ้างถึงอยู่ตรงนี้หรือไม่ ผลว่างอาจแปลว่าโฟลเดอร์ไม่มีไฟล์ที่แสดง ไม่ใช่ AWS พัง')+
box('Terminal · กลับ home','cd ~','cd เปลี่ยน directory ส่วน ~ คือ home ของผู้ใช้ในเครื่องที่กำลังรัน ไม่จำเป็นต้องเป็น home บน Mac')+
box('Terminal · หา AWS CLI','command -v aws','แสดง path ถ้า shell หา aws พบ หากว่างแปลว่ายังหาไม่พบ อาจไม่ได้ติดตั้งหรือ PATH ยังไม่ถูก ไม่ได้บอกว่ามีสิทธิ์ AWS หรือไม่')+
box('Terminal · ดูรุ่น CLI','aws --version','ทำหลังหา aws พบ ควรเห็นข้อความ aws-cli/... การเห็นเวอร์ชันยืนยันแค่โปรแกรมทำงาน ไม่ยืนยันบัญชี region หรือ credentials')+
'<p>ถ้าเห็น <code>%</code> หรือ <code>$</code> หน้าบรรทัดในเอกสาร นั่นมักเป็น prompt ไม่ต้องพิมพ์ตาม ตัวอย่างที่ปุ่มคัดลอกให้ไม่มี prompt นำหน้า</p>')+
panel('4 · อ่านคำสั่งเป็นชิ้น ไม่ต้องท่อง','<p>โครงทั่วไปคือ <code>aws → service → operation → options</code> เช่นชื่อบริการ <code>bedrock-agentcore-control</code> และ operation <code>get-agent-runtime-endpoint</code> ใช้กับการดูรายละเอียด endpoint ตาม API ไม่ใช่การส่งข้อความให้ agent</p><dl><dt>aws</dt><dd>ชื่อโปรแกรมที่ shell จะเรียก</dd><dt>service</dt><dd>บริการที่จะทำงานด้วย เช่น sts, logs, codepipeline หรือ bedrock-agentcore-control</dd><dt>operation</dt><dd>สิ่งที่จะทำ เช่น get/list/describe โดยทั่วไปเป็นการอ่าน ส่วน create/update/delete/start ต้องตรวจผลกระทบ การ invoke agent ก็อาจทำให้ agent เรียก tool ที่เปลี่ยนข้อมูลได้</dd><dt>--region</dt><dd>เลือกภูมิภาคที่คำสั่งจะติดต่อ ต้องตรงกับแล็บ ไม่เดาจาก URL ที่เปิดบทเรียน</dd><dt>--profile</dt><dd>เลือกชุดการตั้งค่าที่มีอยู่ ไม่ใช่ชื่อ endpoint dev/staging/prod และไม่ได้สร้างสิทธิ์ขึ้นมาเอง</dd><dt>--output json</dt><dd>แสดงผลเป็น JSON คือข้อมูลแบบ key/value ที่โปรแกรมอ่านต่อได้</dd><dt>--query</dt><dd>เลือกหรือจัดรูปผลลัพธ์ด้วย JMESPath ไม่ใช่ SQL และไม่ใช่การแก้ข้อมูลต้นทาง</dd></dl>'+
box('Terminal · อ่าน help ในเครื่อง','aws help','เปิดคำอธิบาย CLI ไม่เรียก API ของแล็บ ถ้าเข้าเครื่องมืออ่านหน้าข้อความ กด q เพื่อออก หาก help เปิดไม่ได้อาจขาดตัวแสดงคู่มือ ให้ดูเอกสารทางการแทน')+
box('Terminal · อ่าน help ของ operation','aws bedrock-agentcore-control get-agent-runtime-endpoint help','คำว่า help ท้ายบรรทัดทำให้เป็นการอ่านคู่มือ ไม่ใช่เรียกดู endpoint จริง ถ้า CLI ไม่รู้จัก service/operation ให้เทียบเวอร์ชันกับแล็บก่อนอัปเดตบนเครื่องบริษัท')+
'<p>หน้านี้ให้คัดลอกเฉพาะตัวอย่างที่ไม่เรียก AWS จริง เมื่อต้องอ่าน resource ของแล็บ ให้ใช้คำสั่งจาก workshop หลังตรวจบัญชี region และสิทธิ์กับผู้สอนแล้ว</p>')+
panel('5 · ตัวแปร $... คืออะไร','<p>ตัวแปรคือชื่อที่ shell ใช้เก็บค่า เช่น NEW_VERSION เก็บหมายเลขเวอร์ชัน การเขียน $NEW_VERSION คือขอค่าที่เก็บไว้ ไม่ใช่ให้ AWS ค้นเวอร์ชันใหม่ให้ และเครื่องหมาย $ ในตำแหน่งนี้ไม่ใช่ prompt</p>'+
box('Terminal · ทดลองตัวแปรสมมติ','DEMO_VERSION="example-only"\nprintf "Value: %s\\n" "$DEMO_VERSION"','กำหนดค่าจำลองและแสดง Value: example-only ไม่ใช่หมายเลข Runtime จริง ตอนกำหนดค่าไม่มีช่องว่างข้าง = และตอนอ่านใช้ $')+
'<dl><dt>export</dt><dd>ทำให้โปรแกรมลูกที่เปิดจาก shell นี้เห็นตัวแปรด้วย ไม่ได้ส่งไปทุก Terminal หรือบันทึกถาวรอัตโนมัติ</dd><dt>เครื่องหมายคำพูด</dt><dd>Double quotes ให้ขยาย $ตัวแปร ส่วน single quotes เก็บข้อความตามตัวอักษร ครอบ path หรือค่าที่อาจมีช่องว่าง</dd><dt>backslash ที่ท้ายบรรทัด</dt><dd>ใน Bash/zsh ใช้ต่อคำสั่งหลายบรรทัด ต้องเป็นอักขระสุดท้าย ไม่เว้นช่องว่างหลังมัน หากยังไม่คล่องให้อ่านทั้งชุดก่อนวาง</dd><dt>$(...)</dt><dd>รันคำสั่งข้างในแล้วนำผลมาแทนที่ จึงไม่ใช่ข้อความเฉย ๆ อย่าวางโดยไม่อ่านสิ่งที่อยู่ข้างใน</dd></dl><p>ถ้า NEW_VERSION ว่าง อย่าใส่เลขเดา เปิด <a href="/agentops/debug.html#variables">ตัวอย่างตรวจค่าว่าง</a> แล้วตรวจค่าจากแล็บ ตัวแปรจำลองข้างบนใช้กับ pipeline จริงไม่ได้</p>')+
panel('6 · พื้นฐาน AWS ที่ต้องแยกให้ได้','<dl><dt>Account · บัญชีทรัพยากร</dt><dd>ขอบเขตบัญชีที่ทรัพยากรและสิทธิ์อยู่ แล็บอาจให้บัญชีชั่วคราว ต้องรู้ว่าใช้ของแล็บ ไม่ใช่ของบริษัทหรือส่วนตัวโดยเผลอ</dd><dt>Region · ภูมิภาค</dt><dd>บริการและ resource จำนวนมากอยู่ตาม region หา resource ไม่เจออาจเป็นเพราะเลือกคนละ region ไม่ได้แปลว่าถูกลบ</dd><dt>IAM / role · ตัวตนและสิทธิ์</dt><dd>กำหนดว่าใครทำอะไรได้ การล็อกอินสำเร็จไม่แปลว่ามีสิทธิ์ทุก operation</dd><dt>Credentials · หลักฐานยืนยันตัวตน</dt><dd>อาจเป็นข้อมูลชั่วคราวจากแล็บหรือ SSO ตามทีม ไม่ใช่รหัสผ่านเว็บไซต์ที่นำไปใส่คำสั่งตรง ๆ ไม่แปะค่าเหล่านี้ในเว็บหรือแชต</dd><dt>Profile · ชุดตั้งค่า CLI</dt><dd>มีชื่อใช้เลือก configuration ในเครื่องนั้น การเลือก profile กับการเลือก endpoint prod เป็นคนละชั้น</dd><dt>ARN / resource ID</dt><dd>ARN เป็นรูปแบบอ้างอิงทรัพยากร ส่วน resource ID เป็นตัวระบุของบริการ อย่าใช้แทนกันโดยไม่ดู parameter และไม่ต้องนำค่าจริงมาใส่คู่มือนี้</dd></dl><p>ลำดับที่ควรรู้ก่อนเรียก API: <strong>เครื่องที่รัน → ตัวตน/บัญชี → region → resource → operation</strong></p>')+
panel('7 · ต้องติดตั้งบน Mac ไหม?','<p><strong>ยังไม่จำเป็น ถ้า workshop มี Terminal พร้อมใช้และให้ทำในนั้น</strong> ใช้สภาพแวดล้อมที่ผู้สอนกำหนดก่อน ถ้าทีมให้ทำจาก Mac บริษัทจึงตรวจพอร์ทัลแอปหรือขอ IT ติดตั้ง AWS CLI v2 ตามช่องทางที่อนุญาต</p><ol><li>ตรวจ command -v aws กับ aws --version ก่อน ไม่ติดตั้งซ้ำโดยไม่รู้ของเดิม</li><li>หากต้องติดตั้ง ใช้ installer macOS จากเอกสาร AWS ทางการตามสิทธิ์บริษัท ไม่ต้องติดตั้งผ่าน pip เพียงเพราะใช้ Python</li><li>เปิด Terminal ใหม่และตรวจเวอร์ชันอีกครั้ง</li><li>ตั้งการเข้าใช้งานตามวิธีแล็บ/ทีม เช่น IAM Identity Center หรือสิทธิ์ชั่วคราว อย่าสร้าง long-lived access key เองเพื่อแก้ปัญหา</li></ol><p>aws configure sso และ aws sso login เป็นขั้นตอนตั้งค่า/เข้าสู่ระบบเมื่อทีมใช้ SSO และมีข้อมูลที่ถูกต้อง ไม่ใช่คำสั่งที่ทุกแล็บต้องรัน บางแล็บเตรียม role ไว้แล้วจึงใช้วิธีต่างกัน</p>')+
panel('8 · อ่าน JSON และ error ให้เป็น','<p>JSON ใช้ปีกกาเก็บ object, ชื่อ field ในเครื่องหมายคำพูด และ : คั่นค่า เช่น <code>{"status":"READY","amount_cents":25000}</code> นี่เป็นตัวอย่างสมมติ ไม่ใช่ output API จริง ตัวเลข 25000 ต่างจากข้อความ "25000" โดยเฉพาะเวลาตรวจ type ใน policy</p><dl><dt>command not found: aws</dt><dd>shell หาโปรแกรมไม่พบ ตรวจการติดตั้ง/PATH ไม่ใช่แก้ IAM</dd><dt>Unable to locate credentials</dt><dd>CLI หา credentials ใช้งานไม่ได้ ตรวจวิธีเข้าสู่ระบบของแล็บ ไม่ใช่สร้าง key ใหม่ทันที</dd><dt>ExpiredToken / session หมดอายุ</dt><dd>ตรวจและต่ออายุผ่านวิธีที่ทีมกำหนด ไม่แก้ด้วยเปลี่ยน region สุ่ม</dd><dt>AccessDenied</dt><dd>การเรียกถูกปฏิเสธด้านสิทธิ์ ต้องดู identity/resource/action ไม่เติม sudo เพราะ sudo บน Mac ไม่เพิ่มสิทธิ์ AWS</dd><dt>ResourceNotFound</dt><dd>ตรวจบัญชี region และ ID ก่อนสรุปว่าทรัพยากรหาย</dd><dt>ValidationException</dt><dd>Input ไม่ผ่านเงื่อนไขที่บริการตรวจ ต้องอ่านข้อความส่วนที่ระบุ field เช่น invalid span(s) ไม่ได้หมายถึง agent สอบตก</dd></dl>')+
panel('9 · ลำดับอ่านสำหรับคนเริ่มจากศูนย์','<ol><li>วันนี้: รู้ว่า Terminal ของ Mac กับของแล็บอยู่ที่ไหน</li><li>ลอง pwd, ls และตัวแปรจำลองให้เข้าใจ</li><li>ตรวจ aws --version และอ่าน help ในสภาพแวดล้อมที่ผู้สอนให้</li><li>อ่านคำศัพท์ Account/Region/role แล้วไป <a href="/agentops/glossary.html">Runtime, Gateway, policy และ span</a></li><li>เล่น <a href="/agentops/simulator.html">ห้องจำลอง</a> แล้วค่อยเปิด checklist แก้เคส $250</li></ol><p>ถ้าติดเรื่องแป้นพิมพ์หรือโฟลเดอร์ ให้เปิด <a href="/mac/terminal.html">Terminal บน Mac ตั้งแต่ศูนย์</a> และ <a href="/mac/files-cli.html">คำสั่งจัดไฟล์</a> เพิ่มได้</p>')+
'<div class="sources"><strong>เอกสารทางการ</strong><a href="https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html">AWS CLI · ติดตั้งบน macOS</a><a href="https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-authentication.html">AWS CLI · ตัวตนและ credentials</a><a href="https://docs.aws.amazon.com/cli/latest/reference/bedrock-agentcore-control/get-agent-runtime-endpoint.html">AWS CLI · endpoint operation และ help</a></div>';
}

