import fs from 'node:fs/promises';
const root=new URL('../',import.meta.url),out=new URL('mac/',root);
await fs.mkdir(out,{recursive:true});
const chapters=JSON.parse(await fs.readFile(new URL('mac-content.json',import.meta.url),'utf8'));
const extras=JSON.parse(await fs.readFile(new URL('mac-explanations.json',import.meta.url),'utf8'));
for(const c of chapters)c.sections.push(...(extras[c.slug]||[]));
const {commands,shortcuts}=JSON.parse(await fs.readFile(new URL('mac-reference.json',import.meta.url),'utf8'));
const refs={apple:['Apple · Mac User Guide','https://support.apple.com/guide/mac-help/welcome/mac'],keys:['Apple · Keyboard shortcuts','https://support.apple.com/en-us/102650'],terminal:['Apple · Terminal User Guide','https://support.apple.com/guide/terminal/welcome/mac'],vscode:['VS Code · macOS setup','https://code.visualstudio.com/docs/setup/mac'],python:['Python · venv','https://docs.python.org/3/library/venv.html'],git:['Git · tutorial','https://git-scm.com/docs/gittutorial'],brew:['Homebrew · installation','https://docs.brew.sh/Installation'],docker:['Docker · Mac installation','https://docs.docker.com/desktop/setup/install/mac-install/'],node:['Node.js · download','https://nodejs.org/en/download'],csv:['Python · CSV','https://docs.python.org/3/library/csv.html']};
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const link=(slug)=>'/mac/'+(slug==='index'?'':slug+'.html');
const all=[{slug:'index',title:'เริ่มอ่านและค้นหาทั้งเล่ม'},...chapters,{slug:'atlas',title:'Command Atlas · คำสั่งและปุ่มลัด'}];
const nav=slug=>all.map(c=>'<a href="'+link(c.slug)+'"'+(c.slug===slug?' aria-current="page"':'')+'>'+esc(c.title)+'</a>').join('');
function command(c,i){return '<section class="command" id="command-'+i+'"><div class="command-top"><div><span class="tag">'+esc(c[2].startsWith('ไฟล์')?c[2]:'Terminal · '+c[2])+'</span><h3>'+esc(c[0])+'</h3></div><button type="button" class="copy">คัดลอก</button></div><pre><code>'+esc(c[1])+'</code></pre><p>'+esc(c[3])+'</p><span class="copy-status" role="status"></span></section>';}
const cards=chapters.map(c=>'<a class="card chapter" href="'+link(c.slug)+'"><h2>'+esc(c.title)+'</h2><p>'+esc(c.intro)+'</p><strong>เปิดบทเรียน →</strong></a>').join('');
const keytable='<div class="keys">'+shortcuts.map(x=>'<div><kbd>'+esc(x[0])+'</kbd><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
const sourceKeys={start:['apple','terminal'],keyboard:['keys','apple'],windows:['apple'],finder:['keys','apple'],apps:['apple','vscode'],vscode:['vscode'],python:['python'], 'dev-tools':['git','node','brew','docker'],project:['csv','python']};
function layout(slug,title,body){
return '<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="คู่มือ Mac M1 สำหรับคนย้ายจาก Windows พร้อม Terminal และงาน AI Automation"><title>'+esc(title)+' · Mac Field Guide</title><link rel="stylesheet" href="/mac/style.css"><script src="/mac/app.js" defer></script></head><body><a class="skip" href="#main">ข้ามไปเนื้อหา</a><header><a href="/mac/" class="brand"><b>⌘</b><span>MAC FIELD GUIDE<small>จาก Windows สู่เครื่องทำงานของเรา</small></span></a><a href="/">ชั้นหนังสือ ↗</a></header><div class="shell"><aside><nav aria-label="บทเรียน">'+nav(slug)+'</nav></aside><main id="main"><details class="mobile-menu"><summary>สารบัญ · ทุกบทเรียน</summary>'+nav(slug)+'</details><div class="searchbox"><label for="search">ค้นทั้งเล่ม · ชื่อคำสั่ง อาการ หรือภาษาไทย</label><div class="searchrow"><input id="search" type="search" placeholder="เช่น เปิดไฟล์, PATH, command not found" autocomplete="off"><button id="clear-search" type="button">ล้าง</button></div><p id="search-status" role="status"></p><div id="search-results"></div></div><div class="eyebrow">APPLE SILICON M1 · เรียนทีละขั้น / เปิดค้นตอนใช้งาน</div><h1>'+esc(title)+'</h1>'+body+'<footer>คู่มือภาษาไทยสำหรับเครื่องบริษัท · เมนูและสิทธิ์อาจต่างตามรุ่น/นโยบาย<br><a href="/automation/">อ่านต่อ: AI & Automation ในองค์กร</a> · <a href="/mac/atlas.html">เปิด Command Atlas</a><br>เอกสารอ้างอิงตรวจ 15 กันยายน 2026 · ทดสอบเว็บและตัวอย่าง Python โดยไม่ได้รันคำสั่ง macOS บน Mac จริง</footer></main></div></body></html>';
}
const search=[];
for(let i=0;i<chapters.length;i++){
const c=chapters[i],cmd=commands[c.slug]||[];
const sections=c.sections.map(([h,p],n)=>{search.push({title:h,chapter:c.title,text:p,url:link(c.slug)+'#section-'+n});return '<section class="card" id="section-'+n+'"><h2>'+esc(h)+'</h2><p>'+esc(p)+'</p></section>';}).join('');
cmd.forEach((x,n)=>search.push({title:x[0],chapter:c.title,text:x.slice(1).join(' '),url:link(c.slug)+'#command-'+n}));
const source=(sourceKeys[c.slug]||['terminal','apple']).map(k=>'<a href="'+refs[k][1]+'">'+refs[k][0]+'</a>').join(' · ');
const body='<p class="lead">'+esc(c.intro)+'</p><div class="toc"><strong>ในหน้านี้</strong>'+c.sections.map(([h],n)=>'<a href="#section-'+n+'">'+esc(h)+'</a>').join('')+(cmd.length?'<a href="#commands">ตัวอย่างพร้อมคำอธิบาย</a>':'')+'</div>'+sections+(c.slug==='keyboard'?keytable:'')+(cmd.length?'<h2 id="commands">ตัวอย่าง · อ่านผลก่อนทำขั้นถัดไป</h2><p>ป้าย “ไฟล์” ให้วางใน editor ส่วนป้าย “Terminal” พิมพ์ใน shell อ่านผลกระทบก่อนคัดลอก และรันทีละบรรทัดเมื่อยังไม่คุ้น</p>'+cmd.map(command).join(''):'')+'<section class="practice"><h2>ลองอธิบายให้ตัวเองฟัง</h2><p>เลือกหนึ่งขั้นตอนในบทนี้ บอกว่าทำเพื่ออะไร ต้องเริ่มจากที่ไหน และตรวจอย่างไรว่าสำเร็จ ถ้ายังตอบไม่ได้ ให้กลับไปอ่านคำอธิบายส่วนนั้นก่อนทำกับไฟล์งานจริง</p></section><p class="sources">อ่านรายละเอียดและเมนูปัจจุบันจากต้นฉบับ: '+source+'</p><div class="pager"><a href="'+link(i?chapters[i-1].slug:'index')+'">← บทก่อนหน้า</a><a href="'+link(i<chapters.length-1?chapters[i+1].slug:'atlas')+'">บทถัดไป →</a></div>';
await fs.writeFile(new URL(c.slug+'.html',out),layout(c.slug,c.title,body));
}
shortcuts.forEach(x=>search.push({title:x[0],chapter:'ปุ่มลัด',text:x[1],url:'/mac/atlas.html#shortcuts'}));
await fs.writeFile(new URL('index.html',out),layout('index','ใช้ Mac ให้คล่อง แล้วค่อยต่อยอดเป็นงาน','<p class="lead">หนังสือสำหรับต้า — เริ่มจาก Windows มาสู่ Mac M1 ที่บริษัทดูแล อธิบายสิ่งที่ต้องทำ เหตุผล ผลที่ควรเห็น และวิธีตรวจเมื่อไม่เหมือนตัวอย่าง</p><section class="focus"><span class="tag">เริ่มวันนี้ · 30–45 นาที</span><h2>เปิดแอป → หาไฟล์ → รันงาน → ตรวจผล</h2><p>อ่านบท 00–02 ให้ใช้เครื่องได้ก่อน ตามด้วย Finder และ Terminal แล้วเลือก VS Code/Python ตามเครื่องมือที่ทีมอนุญาต ส่วน Git, Docker และ environment ขั้นลึกเปิดเมื่อเจองานที่ต้องใช้</p><a class="button" href="/mac/start.html">เริ่มบทแรก →</a> <a href="/mac/atlas.html">มีปัญหาอยู่แล้ว? เปิด Atlas</a></section><section class="card"><h2>เส้นทางตามเวลาที่มี</h2><p><strong>10 นาที:</strong> ปุ่มลัด เปิดแอป สลับภาษา ล็อกเครื่อง และหาไฟล์<br><strong>หนึ่งช่วงเย็น:</strong> Terminal → จัดไฟล์ → อ่าน log → PATH<br><strong>พร้อมเริ่มโค้ด:</strong> VS Code → Python → CSV Report<br><strong>ระหว่างทำงาน:</strong> ค้นชื่อ error แล้วเปิดบทที่ตรงอาการ</p><p>macOS 26.6.2 เป็นเวอร์ชันที่ผู้ใช้แจ้ง โปรดยืนยันที่ About This Mac คำสั่งที่เปลี่ยนไฟล์มีป้ายบอก และตัวอย่างใช้ข้อมูลจำลอง</p></section><div class="chapters">'+cards+'</div>'));
const atlas=Object.entries(commands).map(([slug,items])=>'<h2>'+esc(chapters.find(c=>c.slug===slug).title)+'</h2>'+items.map((x,n)=>'<article class="card"><a href="'+link(slug)+'#command-'+n+'"><strong>'+esc(x[0])+'</strong></a><p>'+esc(x[2])+' · '+esc(x[3])+'</p><code>'+esc(x[1].split('\n')[0])+'</code></article>').join('')).join('');
await fs.writeFile(new URL('atlas.html',out),layout('atlas','Command Atlas · หาให้เจอไว','<p class="lead">ค้นด้านบนได้ทั้งคำสั่ง ภาษาไทย และ error กดชื่อรายการเพื่ออ่านตัวอย่างเต็มพร้อมผลกระทบก่อนคัดลอก</p><h2 id="shortcuts">ปุ่มลัดใช้ประจำ</h2>'+keytable+atlas));
await fs.writeFile(new URL('search.json',out),JSON.stringify(search));
console.log('Built '+all.length+' pages; '+search.length+' search entries');
