(()=>{'use strict';
const page=document.body.dataset.page,valid=['index','basics','glossary','modules','simulator','debug','talk','quiz'];
const key='agentops-field-notes-v2';let state={read:{},checks:{}},persist=true;
try{const parsed=JSON.parse(localStorage.getItem(key)||'null');if(parsed&&typeof parsed==='object'&&parsed.read&&parsed.checks){state={read:parsed.read,checks:parsed.checks};}}catch{persist=false;}
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{persist=false;}if(!persist)document.querySelector('#storage-note').textContent='Browser ไม่อนุญาตเก็บข้อมูล: ใช้งานได้ในหน้านี้ แต่ความคืบหน้าอาจไม่อยู่หลังปิด';}
function renderProgress(){const n=valid.filter(x=>state.read[x]===true).length;document.querySelector('#reading-progress').value=n;document.querySelector('#reading-count').textContent=n+' / 8 หน้า';document.querySelector('#mobile-reading-count').textContent='อ่านแล้ว '+n+' / 8 หน้า';document.querySelector('#mark-read').checked=state.read[page]===true;}
renderProgress();if(!persist)save();
document.querySelector('#mark-read').addEventListener('change',event=>{state.read[page]=event.target.checked;save();renderProgress();});
document.querySelectorAll('[data-check]').forEach(el=>{el.checked=state.checks[el.dataset.check]===true;el.addEventListener('change',()=>{state.checks[el.dataset.check]=el.checked;save();});});
document.querySelectorAll('.copy').forEach(button=>button.addEventListener('click',async()=>{const box=button.closest('.copybox'),content=box.querySelector('code,.copy-content'),status=box.querySelector('.copy-status');try{await navigator.clipboard.writeText(content.textContent);status.textContent='คัดลอกแล้ว';}catch{const r=document.createRange();r.selectNodeContents(content);const s=window.getSelection();s.removeAllRanges();s.addRange(r);status.textContent='เลือกข้อความแล้ว กด Command+C หรือ Ctrl+C เพื่อคัดลอก';}}));
const term=document.querySelector('#term-search');
if(term)term.addEventListener('input',()=>{const words=term.value.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);let n=0;document.querySelectorAll('.term').forEach(el=>{el.hidden=!words.every(w=>el.textContent.toLocaleLowerCase().includes(w));if(!el.hidden)n++;});document.querySelector('#term-count').textContent=n+' คำ';document.querySelector('#term-empty').hidden=n!==0;});
if(page==='simulator'){
const cases=window.AGENTOPS_DATA.cases,select=document.querySelector('#case-select');let step=0;
function draw(){const c=cases.find(x=>x.id===select.value);document.querySelector('#case-expected').textContent=c.expected;document.querySelector('#case-observed').textContent=c.observed;document.querySelector('#step-count').textContent='ขั้น '+(step+1)+' / '+c.steps.length+' · เส้นทางเพื่อเรียนรู้';document.querySelector('#step-title').textContent=c.steps[step][0];document.querySelector('#step-text').textContent=c.steps[step][1];document.querySelector('#step-prev').disabled=step===0;document.querySelector('#step-next').disabled=step===c.steps.length-1;document.querySelector('#step-next').textContent=step===c.steps.length-1?'ครบทุกขั้นแล้ว':'ขั้นถัดไป →';const list=document.querySelector('#step-list');list.replaceChildren();c.steps.forEach((s,i)=>{const li=document.createElement('li');li.textContent=(i+1)+'. '+s[0];if(i===step)li.setAttribute('aria-current','step');list.append(li);});}
select.addEventListener('change',()=>{step=0;draw();});document.querySelector('#step-prev').addEventListener('click',()=>{if(step>0)step--;draw();});document.querySelector('#step-next').addEventListener('click',()=>{const c=cases.find(x=>x.id===select.value);if(step<c.steps.length-1)step++;draw();});document.querySelector('#step-reset').addEventListener('click',()=>{step=0;draw();});draw();}
if(page==='quiz'){
const answers=new Map(),questions=window.AGENTOPS_DATA.quiz;
function score(){let correct=0;answers.forEach((a,i)=>{if(a===questions[i][2])correct++;});document.querySelector('#quiz-score').textContent='ตอบแล้ว '+answers.size+' / '+questions.length+' · ถูก '+correct+' ข้อ'+(answers.size===questions.length?' · อ่านเหตุผลของข้อที่พลาดก่อนเริ่มใหม่':'');}
document.querySelectorAll('.question').forEach(box=>{const i=Number(box.dataset.question);box.querySelectorAll('.answer').forEach(button=>button.addEventListener('click',()=>{if(answers.has(i))return;const choice=Number(button.dataset.answer),correct=questions[i][2];answers.set(i,choice);box.querySelectorAll('.answer').forEach(b=>{b.disabled=true;if(Number(b.dataset.answer)===correct)b.classList.add('correct');});if(choice!==correct)button.classList.add('wrong');const feedback=box.querySelector('.feedback');feedback.hidden=false;feedback.textContent=(choice===correct?'ตอบถูก — ':'ยังไม่ถูก — คำตอบที่ถูก: '+questions[i][1][correct]+' · ')+questions[i][3];score();}));});
document.querySelector('#quiz-reset').addEventListener('click',()=>{answers.clear();document.querySelectorAll('.answer').forEach(b=>{b.disabled=false;b.classList.remove('correct','wrong');});document.querySelectorAll('.feedback').forEach(f=>{f.hidden=true;f.textContent='';});score();document.querySelector('.answer').focus();});}
})();
